name = "fpm-modules"
version = "./VERSION"
license = "license"
author = "davidpfister"
maintainer = "davidpfister"
copyright = "Copyright 2025, davidpfister"
description = "Generate dependency graphs of Fortran modules"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[preprocess]
cpp.suffixes = ["F90", "f90", "c"]
cpp.macros = ["_FPM","_VERSION=\"'{version}'\""]

[dependencies]
fpm = {git = "https://github.com/fortran-lang/fpm", tag="v0.12.0"}

[[test]]
name = "test"
source-dir="./test"
main = "main.f90"